# Generated by Django 4.2.3 on 2023-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expected Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='participant_expected_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Expected Number of Participants'),
        ),
    ]
